# Generated by Django 4.1 on 2022-08-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
